export const abbreviationArray = [
"idk",
"sry",
"ATM",
"IMO",
"JIC",
"WTH",
"A3",
"BC",
"BM",
"B4",
"B/C" ,
"Bc",
"BB" ,
"BD" ,
"BF",
"BG",
"B/W",
"CU" ,
"DM",
"KMP",
"DL",
"EM",
"FB",
"GF",
"GG",
"GM",
"GN",
"CYL",
"HF",
"HU",
"IC",
"IS",
"IM",
"JJ",
"JK",
"KK",
"KU",
"L8",
"LU",
"LI",
"MT",
"M",
"F",
"M8" ,
"MU" ,
"NP" ,
"OH" ,
"O3" ,
"OT" ,
"OP" ,
"PM" ,
"R8" ,
"RT" ,
"RL" ,
"SD" ,
"SS" ,
"SU" ,
"TY" ,
"TC" ,
"ASAP",
"AKA",
"BTW",
"BOT",
"CTS",
"DIY",
"F2F",
"FYEO",
"G2B",
"GTG",
"IDC",
"L8R",
"LMK",
"S2R",
"TMI",
"WTF",
"SMH",
"ASL",
"HTH",
"IRL",
"ITT",
"LDR",
"NVM",
"Pic",
"PPL",
"PLZ",
"TTYL",
"W8" ,
"YW" ,
"AFK",
"BMT",
"HBU",
"LMS",
"SOS" ,
"POS" ,
"BRB",
"FYI",
"GR8",
"LOL",
"LMAO",
"MSG",
"IDK",
"NSFW",
"AFC",
"CYS",
"FWD",
"DND",
"HAND",
"JAM",
"LMA",
"OMG",
"TXT",
"OMW",
"TTYS",
"AAB",
"ADL",
"AEAP",
"BBIAB",
"CYA",
"FWIW",
"GIYF",
"ICYDK",
"ILY",
"IYDMM",
"LTNS",
"MYOB",
"STR8",
"WB",
"WDUWT",
"1NAM",
"BFF",
"BEG",
"CYO",
"DQMOT",
"HMU",
"WRU",
"BBL",
"EOS",
"GAL",
"LMHO",
"Q4U",
"5N" ,
"KYP",
"ORLY",
"YT" ,
"AAK",
"ANY1",
"BFN",
"Dunno",
"FTL",
"GFY",
"GTH",
"ICQ",
"JOOC",
"NE1",
"NOYB",
"SRY",
"SWW",
"SUP",
"TG" ,
"TIA",
"YCM",
"2MORO",
"ASIC",
"BAU",
"DIKU",
"GNASD",
"PMSL",
"YSIC",
"AAMOF",
"CUL",
"FAQ",
"LAM",
"TCO",
"TYT",
"Fab",
"ROFL",
"THX",
"AAR",
"AEAE",
"BBS",
"EOM",
"GBTW",
"Gunna",
"Gonna",
"IDGI",
"NWS",
"RIP",
"Sec",
"Tho",
"WD" ,
"YSVW",
"2N8",
"BMS",
"EMFBI",
"404",
"RSVP",
"LLAH",
"IIRC",
"FTW",
"Cause",
"Coz",
"Cuz" ,
"AFAIC",
"BA3",
"LNG",
"CFY",
"W8AM",
"IACL",
]
export const abbreviationObj = {
"ATM":"At the moment",
"IMO":"In my opinion",
"JIC":"Just in case",
"WTH":"What the h*ll",
"A3": "Anywhere, anytime, any place",
"BC": "Be cool",
"BM": "Bite me",
"B4": "Before",
"B/C" : "Because",
"Bc": "Because",
"BB": "Bye Bye",
"BD": "Big deal",
"BF" :"Boyfriend, or best friend",
"BG":"Big grin",
"B/W":"Between",
"CU": "See you",
"DM":"Direct message",
"KMP":"Keep me posted",
"DL": "Dead link",
"EM": "Email",
"FB": "Facebook",
"GF": "Girlfriend",
"GG": "Good game",
"GM": "Good morning",
"GN": "Goodnight",
"CYL":" Call you later",
"HF": "Have fun",
"HU": "Hug you",
"IC": "I see",
"IS": "I’m sorry",
"IM": "Instant message",
"JJ": "Just joking",
"JK": "Just kidding",
"KK": "Okay cool",
"KU": "Kiss you",
"L8": "Late",
"LU": "Love you",
"LI": "LinkedIn",
"MT": "Modified tweet",
"M":"Male",
"F":"Female",
"M8": "Mate",
"MU": "Miss you",
"NP": "No problem",
"OH": "Overheard",
"O3": "Out of office",
"OT": "Off topic",
"OP": "Original poster",
"PM": "Private message",
"R8": "Right",
"RT": "Retweet",
"RL": "Real life",
"SD": "Sweet dreams",
"SS": "So sorry",
"SU": "Shut up",
"TY": "Thank you",
"TC": "Take care",
"ASAP": "As soon as possible",
"AKA":"Also known as",
"BTW":"By the way",
"BOT":"Back on topic",
"CTS":"Changing the subject",
"DIY":"Do it yourself",
"F2F":"Face to face",
"FYEO": "For your eyes only",
"G2B":"Going to bed",
"GTG":"Got to go",
"IDC":"I don’t care",
"L8R":"Later",
"LMK":"Let me know",
"S2R":"Send to receive",
"TMI":"Too much information",
"WTF":"What the f*ck",
"SMH":"Shaking my head",
"ASL":"Age/Sex/Location",
"HTH":"Here to help (can also be used as happy to help)",
"IRL":"In real life",
"ITT":"In this thread",
"LDR":"Long distance relationship",
"NVM":"Nevermind",
"Pic":"Picture",
"PPL":"People",
"PLZ":"Please",
"TTYL": "Talk to you later",
"W8" :"Wait",
"YW" :"You’re welcome",
"AFK":"Away from keyboard",
"BMT":"Before my time",
"HBU":"How about you",
"LMS":"Like my status",
"SOS" : "Someone on shoulder",
"POS" : "Parents on shoulder",
"BRB":"Be right back",
"FYI":"For your information",
"GR8":"Great",
"LOL":"Laughing out loud",
"LMAO" :"Laughing my a*s off",
"MSG":"Message",
"IDK":"I do not know",
"NSFW" :"Not safe for work",
"AFC":"Away from computer",
"CYS":"Check your settings",
"FWD":"Forward",
"DND":"Do not disturb",
"HAND": "Have a nice day",
"JAM":"Just a minute",
"LMA":"Leave me alone",
"OMG":"Oh my god",
"TXT":"Text",
"OMW":"On my way",
"TTYS": "Talk to you soon",
"AAB":"Average at best",
"ADL":"All day long",
"AEAP": "As early as possible",
"BBIAB" : "Be back in a bit",
"CYA":"See you again",
"FWIW": "For what it’s worth",
"GIYF": "Google is your friend",
"ICYDK" : "In case you didn’t know",
"ILY":"I love you",
"IYDMMA" : "If you don’t mind me asking",
"LTNS": "Long time no see",
"MYOB": "Mind your own business",
"STR8": "Straight",
"WB":"Welcome back",
"WDUWTA": "What do you want to talk about",
"1NAM": "One in a million",
"BFF":"Best friend forever",
"BEG":"Big evil grin",
"CYO":"See you online",
"DQMOT":"Don’t quote me on this",
"HMU":"Hit me up",
"WRU":"Who are you",
"BBL":"Be back later",
"EOS":"End of story",
"GAL":"Get a life",
"LMHO": "Laughing my head off",
"Q4U":"Question for you",
"5N": "Fine",
"KYP":"Keep you posted",
"ORLY": "Oh really",
"YT" :"Youtube",
"AAK":"Alive and kicking",
"ANY1":"Anyone",
"BFN":"Bye for now",
"Dunno" : "Do not know",
"FTL":"For the loss",
"GFY":"Good for you",
"GTH":"Go to h*ll",
"ICQ":"I seek you",
"JOOC": "Just out of curiosity",
"NE1":"Anyone",
"NOYB":"None of your business",
"SRY":"Sorry",
"SWW":"Sorry wrong window",
"SUP":"What’s up",
"TG" : "That’s great",
"TIA":"Thanks in advance",
"YCM":"You copied me",
"2MORO" : "Tomorrow",
"ASIC": "As soon as I can",
"BAU":"Business as usual",
"DIKU" :"Do I know you",
"GNASD" : "Goodnight and sweet dreams",
"PMSL" :"P*ssing myself laughing",
"YSIC": "Why should I care",
"AAMOF" : "As a matter of fact",
"CUL":"See you later",
"FAQ":"Frequently asked questions",
"LAM":"Leave a message",
"TCO":"Taken care of",
"TYT":"Take your time",
"Fab":"Fabulous",
"ROFL": "Rolling on the floor laughing",
"THX":"Thanks",
"AAR":"At any rate",
"AEAE": "And ever and ever",
"BBS":"Be back soon",
"EOM":"End of message",
"GBTW" :"Get back to work",
"Gunna" : "Going to",
"Gonna": "Going to",
"IDGI": "I don’t get it",
"NWS":"Not work safe",
"RIP":"Rest in peace",
"Sec":"Second",
"Tho":"Though",
"WD" :"Well done",
"YSVW": "You are so very welcome",
"2N8":"Tonight",
"BMS":"Blew my sh*t",
"EMFBI" : "Excuse me for butting in",
"404":"No clue",
"RSVP" : "Response requested",
"LLAH": "Laughing like a hyena",
"IIRC": "If I recall correctly",
"FTW":"For the win",
"Cause" : "Because",
"Coz": "Because",
"Cuz" : "Because",
"AFAIC" : "As far as I’m concerned",
"BA3":"Battery",
"LNG":"Long",
"CFY":"Calling for you",
"W8AM": "Wait a minute",
"IACL": "I am currently laughing",
}



